import json
import math
import random
import requests

url = 'http://localhost:3000/xychart'

def r():
    return random.randrange(-1000, 1000)

colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']

def rc():
    return random.choice(colors)

fn = ['alice', 'bob', 'charlie', 'dave', 'ed', 'fred', 'george']
ln = ['zulu', 'yankee', 'xray', 'whiskey', 'victor', 'uniform']

def rn():
    return random.choice(fn) + '.' + random.choice(ln) + '.' + str(random.randrange(1000,9999))

points = []
i = 0
n = 500

while (i < n):
    i= i + 1
    new_item = {'name': rn(), 'x': r(), 'y': r(), 'z': r(), 'color': rc()}
    print 'New item:', new_item
    points.append(new_item)

chart_spec = {
    'title': 'Test data generated by testbig.py',
    'banner': 'job:joel54 iteration:32 chi^2: 332.5',
    'points': points
    #'connections': connections
}

payload = json.dumps(chart_spec)
print 'Data length:', len(payload)
#print 'Posting:', data

status = requests.post(url,
                        data=payload,
                        headers={'Content-Type': 'application/json'});
print 'Response:', status
