import json
import math
import random
import requests

url = 'http://localhost:3000/hairball'

def r():
    #return random.randrange(-1000, 1000)
    magnitude = random.randrange(0, 1000)
    magnitude = (magnitude * magnitude) / 1000
    sign = random.choice([1, -1])
    return (magnitude * sign) / 1000

colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']

def rc():
    return random.choice(colors)

fn = ['evil', 'nasty', 'corrupt', 'smelly', 'vile', 'foul', 'fetid', 'rancid', 'stinky']
ln = ['bank', 'utility', 'tech', 'energy', 'industrial', 'service', 'lobbying']
tp = ['corp', 'inc', 'pc', 'ltd']

def rn():
    return random.choice(fn) + '.' + random.choice(ln) + '.' + random.choice(tp) + '.' + str(random.randrange(1000,9999))

num_companies = 500
companies = []
for i in range(num_companies):
    new_company = {'ticker': rn(), 'coords': [r(), r(), r()], 'color': rc()}
    print('New company:', new_company)
    companies.append(new_company)

num_dates = 100
dates = []
def rp():
    return int(random.random() * len(companies))

for i in range(num_dates):
    new_date = {'label': str(i), 'coords': [r(), r(), r()]}
    dates.append(new_date)

chart_spec = {
    'title': 'Test data generated by testbig.py',
    'banner': 'job:joel54 iteration:32 chi^2: 332.5',
    'companies': companies,
    'dates': dates
}

payload = json.dumps(chart_spec)
print('Data length:', len(payload))
#print 'Posting:', data

status = requests.post(url,
                        data=payload,
                        headers={'Content-Type': 'application/json'});
print('Response:', status)
